config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :upload_files

  resources :badge_logs do
    get :autocomplete_user_name, :on => :collection
  end
  resources :badge_conditions
  resources :badge_categories
  resources :badges
  devise_for :users
  resources :work_tasks
  resources :work_processes
  resources :time_management_sheets
  resources :instructions
  resources :avatars

  root 'menu#index'

end

app/controllers/work_processes_controller.rb
class WorkProcessesController < ApplicationController
  before_action :set_work_process, only: [:show, :edit, :update, :destroy]
  before_action :current_admin_check

  # GET /work_processes
  # GET /work_processes.json
  def index
    @work_processes = WorkProcess.all
  end

  # GET /work_processes/1
  # GET /work_processes/1.json
  def show
  end

  # GET /work_processes/new
  def new
    @work_process = WorkProcess.new
  end

  # GET /work_processes/1/edit
  def edit
  end

  # POST /work_processes
  # POST /work_processes.json
  def create
    @work_process = WorkProcess.new(work_process_params)

    respond_to do |format|
      if @work_process.save
        format.html { redirect_to @work_process, notice: 'Work process was successfully created.' }
        format.json { render :show, status: :created, location: @work_process }
      else
        format.html { render :new }
        format.json { render json: @work_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_processes/1
  # PATCH/PUT /work_processes/1.json
  def update
    respond_to do |format|
      if @work_process.update(work_process_params)
        format.html { redirect_to @work_process, notice: 'Work process was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_process }
      else
        format.html { render :edit }
        format.json { render json: @work_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_processes/1
  # DELETE /work_processes/1.json
  def destroy
    @work_process.destroy
    respond_to do |format|
      format.html { redirect_to work_processes_url, notice: 'Work process was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_process
      @work_process = WorkProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_process_params
      params.require(:work_process).permit(:id, :process_code, :status_type, :name)
    end
end

app/helpers/work_processes_helper.rb
module WorkProcessesHelper
end

app/views/work_processes/_form.html.erb
<%= form_for(@work_process) do |f| %>
  <% if @work_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_process.errors.count, "error") %> prohibited this work_process from being saved:</h2>

      <ul>
      <% @work_process.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :process_code %><br>
    <%= f.text_field :process_code %>
  </div>
  <div class="field">
    <%= f.label :status_type %><br>
    <%= f.text_field :status_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_processes/edit.html.erb
<h1>Editing work_process</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_process %> |
<%= link_to 'Back', work_processes_path %>

app/views/work_processes/index.html.erb
<h1>Listing work_processes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Process code</th>
      <th>Status type</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_processes.each do |work_process| %>
      <tr>
        <td><%= work_process.id %></td>
        <td><%= work_process.process_code %></td>
        <td><%= work_process.status_type %></td>
        <td><%= work_process.name %></td>
        <td><%= link_to 'Show', work_process %></td>
        <td><%= link_to 'Edit', edit_work_process_path(work_process) %></td>
        <td><%= link_to 'Destroy', work_process, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work process', new_work_process_path %>

app/views/work_processes/new.html.erb
<h1>New work_process</h1>

<%= render 'form' %>

<%= link_to 'Back', work_processes_path %>

app/views/work_processes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @work_process.id %>
</p>

<p>
  <strong>Process code:</strong>
  <%= @work_process.process_code %>
</p>

<p>
  <strong>Status type:</strong>
  <%= @work_process.status_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @work_process.name %>
</p>

<%= link_to 'Edit', edit_work_process_path(@work_process) %> |
<%= link_to 'Back', work_processes_path %>