config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :upload_files

  resources :badge_logs do
    get :autocomplete_user_name, :on => :collection
  end
  resources :badge_conditions
  resources :badge_categories
  resources :badges
  devise_for :users
  resources :work_tasks
  resources :work_processes
  resources :time_management_sheets
  resources :instructions
  resources :avatars

  root 'menu#index'

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  validates :instruction_code, :uniqueness => true
  
  has_many :time_management_sheets
  
  before_validation :code_padding
  
  def code_padding
    self.instruction_code = format("%07d", self.instruction_code.to_i)
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]
  before_action :current_admin_check

  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = Instruction.all
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    @instruction = Instruction.new
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: 'Instruction was successfully created.' }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url, notice: 'Instruction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instruction_params
      params.require(:instruction).permit(:id, :instruction_code, :status_type, :name)
    end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_form.html.erb
<%= form_for(@instruction) do |f| %>
  <% if @instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% @instruction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instruction_code %><br>
    <%= f.text_field :instruction_code %>
  </div>
  <div class="field">
    <%= f.label :status_type %><br>
    <%= f.text_field :status_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructions/edit.html.erb
<h1>Editing instruction</h1>

<%= render 'form' %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<h1>Listing instructions</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Instruction code</th>
      <th>Status type</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructions.each do |instruction| %>
      <tr>
        <td><%= instruction.id %></td>
        <td><%= instruction.instruction_code %></td>
        <td><%= instruction.status_type %></td>
        <td><%= instruction.name %></td>
        <td><%= link_to 'Show', instruction %></td>
        <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
        <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New instruction</h1>

<%= render 'form' %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @instruction.id %>
</p>

<p>
  <strong>Instruction code:</strong>
  <%= @instruction.instruction_code %>
</p>

<p>
  <strong>Status type:</strong>
  <%= @instruction.status_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @instruction.name %>
</p>

<%= link_to 'Edit', edit_instruction_path(@instruction) %> |
<%= link_to 'Back', instructions_path %>