config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :upload_files

  resources :badge_logs do
    get :autocomplete_user_name, :on => :collection
  end
  resources :badge_conditions
  resources :badge_categories
  resources :badges
  devise_for :users
  resources :work_tasks
  resources :work_processes
  resources :time_management_sheets
  resources :instructions
  resources :avatars

  root 'menu#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :badge_logs
  has_many :badge_conditions
  belongs_to :badge_category
  belongs_to :file, :class_name => 'UploadFile', :foreign_key => 'upload_file_id', :dependent => :destroy
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :badge_category_id, presence: true
  validates :upload_file_id, presence: true
  validates :description, presence: true
  
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]
  before_action :set_badge_categories, only: [:new, :create]
  before_action :current_admin_check

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)
    flag = @badge.save
    @badge.file.destroy if !flag && @badge.file

    respond_to do |format|
      if flag
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
      set_badge_categories
    end
    def set_badge_categories
        @badge_categories = BadgeCategory.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
        #params[:badge]
        if params[:badge][:badge_image]
            uploadfile = UploadFile.save_badge_icon(params[:badge][:badge_image])
            uploadfile.save
            params[:badge][:upload_file_id] = uploadfile.id
        end
        params.require(:badge).permit(:name, :description, :upload_file_id, :badge_category_id)

    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :badge_category_id %><br>
    <%= f.select :badge_category_id, elements_options_for_select(@badge_categories,nil,:name), :include_blank => true %>
  </div>

  <div class="field">
    <%= f.label :badge_image %><br>
    <%= f.file_field  :badge_image %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing badges</h1>
<%= link_to 'New Badge', new_badge_path %>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>CategoryName</th>
      <th>BadgeIcon</th>
      <th>Description</th>
      <th>Created_at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.id %></td>
        <td><%= badge.name %></td>
        <td><%= badge.badge_category.name if badge.badge_category %></td>
        <td><%= image_tag(badge.file.disk_filename, :height => '64') if badge.file %></td>
        <td><%= badge.description %></td>
        <td><%= badge.created_at %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>